//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Agent.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public abstract class Agent implements Steppable {
	protected int virusTimer;
	protected Virologist smearedVirologist;
	protected Virologist crafterVirologist;
	public void smear(Virologist v) {
	}
	
	public void step() {
	}
}
