//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DefaultMove.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class DefaultMove implements Move {
	public void move(Field f, Virologist v) {
	}
}
