//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Field {
	private Virologist virologists;
	protected Field neighbors;
	public void accept(Virologist v) {
	}
	
	public void remove(Virologist v) {
	}
	
	public void interactWithField(Virologist v) {
	}
	
	public void setNeighbor(int idx, Field f) {
	}
}
