//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Game {
	private Map map;
	public void startGame() {
	}
	
	public void endGame() {
	}
}
