//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Laboratory.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Laboratory extends Field {
	private Code code;
	public void interactWithField(Virologist v) {
	}
	
	public void placeCode(Code c) {
	}
}
