//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shelter.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Shelter extends Field {
	private Gear gear;
	public void interactWithField(Virologist v) {
	}
	
	public void addGear(Gear g) {
	}
}
