//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Virologist.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Virologist implements Steppable {
	private int nucleotide;
	private int aminoAcid;
	private int resourceLimit;
	private boolean stunned;
	private Absorb absorbStrats;
	private Agent craftedAgents;
	private Gear gears;
	private Field field;
	private Code learntCodes;
	private Move moveStrat;
	public void move(Field f) {
	}
	
	public void smearAgent(Agent a, Virologist v) {
	}
	
	public void absorb(Agent a) {
	}
	
	public void touch() {
	}
	
	public void loot(Virologist v, Gear g) {
	}
	
	public void pickUpGear(Gear g) {
	}
	
	public void loseGear(Gear g) {
	}
	
	public void learnCode(Code c) {
	}
	
	public void craftAgent(Code c) {
	}
	
	public void addNucleotide(int n) {
	}
	
	public void addAminoAcid(int a) {
	}
	
	public void removeNucleotide(int n) {
	}
	
	public void removeAminoAcid(int a) {
	}
	
	public void step() {
	}
	
	public void forgetCodes() {
	}
	
	public void addCraftedAgent(Agent a) {
	}
	
	public void addAbsorbStrat(Absorb a) {
	}
	
	public void removeAbsorbStrat(Absorb a) {
	}
}
