//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Absorb.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public interface Absorb {
	void absorb(Agent a);
}
