//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AmniCode.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class AmniCode extends Code {
	public void craftAgent(int n, int a) {
	}
}
