//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AmniVirus.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class AmniVirus extends Agent {
	public void smear(Virologist v) {
	}
	
	public void step() {
	}
}
