//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Code.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public abstract class Code {
	protected int nCost;
	protected int aCost;
	public void craftAgent(int n, int a) {
	}
}
