//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DanceVirus.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class DanceVirus extends Agent {
	private DanceMove strat;
	public void smear(Virologist v) {
	}
	
	public void step() {
	}
}
