//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gear.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public abstract class Gear {
	public void giveStat(Virologist v) {
	}
	
	public void removeStat(Virologist v) {
	}
}
