//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Map {
	private int uniqueCodeCount;
	private Field fields;
	public void generateMap() {
	}
}
