//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Move.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public interface Move {
	void move(Field f, Virologist v);
}
