//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProtVaccineAbsorb.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class ProtVaccineAbsorb implements Absorb {
	public void absorb(Agent a) {
	}
}
