//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RobeGear.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class RobeGear extends Gear {
	private RobeAbsorb strat;
	public void giveStat(Virologist v) {
	}
	
	public void removeStat(Virologist v) {
	}
}
