//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public interface Steppable {
	void step();
}
