//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StunCode.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class StunCode extends Code {
	public void craftAgent(int n, int a) {
	}
}
