//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Warehouse.java
//  @ Date : 3/15/2022
//  @ Author : 
//
//




public class Warehouse extends Field implements Steppable {
	private int nProduced;
	private int aProduced;
	public void step() {
	}
	
	public void interactWithField(Virologist v) {
	}
}
